#!/usr/bin/env bash
#
# k8s-bootstrap.sh - Install the whole stack WITHOUT cloning this repo.
#
# Self-contained on purpose: it is meant to be downloaded and run directly,
#   curl -fsSL https://raw.githubusercontent.com/d0whc3r/minecraft-servers/master/scripts/k8s-bootstrap.sh -o k8s-bootstrap.sh
#   bash k8s-bootstrap.sh [namespace]
# (or reviewed and piped: curl -fsSL .../k8s-bootstrap.sh | bash -s -- [namespace]
# — piped runs skip the interactive prompts, pass config via env instead).
#
# What it does:
#   1. Creates the minecraft-shared-env Secret with the server-wide config
#      (EULA, MC_ROUTER_DOMAIN, CF_API_KEY, RCON_PASSWORD...) from flags,
#      environment variables or interactive prompts.
#   2. helm upgrade --install mc-router + web-panel straight from the OCI
#      charts published by CI:
#        oci://ghcr.io/d0whc3r/minecraft-servers/charts/<chart>
#
# The modpack catalog is baked into the panel image, so nothing else is
# needed: start servers from the panel and each becomes a mc-<server> Helm
# release. To update the Secret later, re-run this script with
# FORCE_SHARED_ENV=1 (or --env-file), or use scripts/k8s-sync-configs.sh
# from a repo checkout.
#
# Usage: ./k8s-bootstrap.sh [namespace]
#
# Options:
#   --env-file FILE   extra KEY=VALUE pairs for the shared Secret (same
#                     format as the repo .env; its keys win over defaults)
#
# Environment (all optional):
#   MC_ROUTER_DOMAIN        players connect to <server>.<domain>  (mc.local)
#   MC_ROUTER_PORT          public router port                   (25565)
#   MC_ROUTER_SERVICE_TYPE  LoadBalancer|NodePort|ClusterIP      (LoadBalancer)
#   MC_ROUTER_NODE_PORT     explicit nodePort when type=NodePort
#   CF_API_KEY              CurseForge API key (modpack downloads)
#   RCON_PASSWORD           generated when empty
#   MCPANEL_USER            panel admin user                     (admin)
#   MCPANEL_PASSWORD        generated by the panel when empty (printed in pod logs)
#   K8S_PANEL_HOST          ingress host for the panel (skipped when empty)
#   MC_ROUTER_CHART_VERSION mc-router chart version to install   (pinned below)
#   PANEL_CHART_VERSION     web-panel chart version to install   (pinned below)
#   CHART_OCI_PREFIX        chart registry prefix (forks/mirrors)
#   FORCE_SHARED_ENV=1      overwrite an existing shared Secret
#
# Exit Codes:
#   0 - success
#   1 - general error (missing tools, cluster unreachable, helm failure)

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

error() { echo -e "${RED}ERROR: $1${NC}" >&2; }
info() { echo -e "$1"; }
success() { echo -e "${GREEN}✓ $1${NC}"; }

# Chart versions published by CI (.github/workflows/charts-publish.yml).
# Bump these after a new chart release lands on GHCR.
DEFAULT_ROUTER_CHART_VERSION="0.1.2"
DEFAULT_PANEL_CHART_VERSION="0.1.0"
CHART_OCI_PREFIX="${CHART_OCI_PREFIX:-oci://ghcr.io/d0whc3r/minecraft-servers/charts}"
SHARED_ENV_SECRET="${SHARED_ENV_SECRET:-minecraft-shared-env}"

NAMESPACE="minecraft"
ENV_FILE=""
while [ $# -gt 0 ]; do
  case "$1" in
    --env-file)
      [ $# -ge 2 ] || {
        error "--env-file needs a path"
        exit 1
      }
      ENV_FILE="$2"
      shift 2
      ;;
    -h | --help)
      grep '^#' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    -*)
      error "unknown option: $1"
      exit 1
      ;;
    *)
      NAMESPACE="$1"
      shift
      ;;
  esac
done

for tool in helm kubectl; do
  if ! command -v "$tool" > /dev/null 2>&1; then
    error "$tool is required (kubectl: https://k8s.dev/docs, helm: https://helm.sh)"
    exit 1
  fi
done
if ! kubectl get namespace "$NAMESPACE" > /dev/null 2>&1; then
  info "Creating namespace: $NAMESPACE"
  kubectl create namespace "$NAMESPACE"
fi

# ---------------------------------------------------------------------------
# 1. Shared env Secret: EULA, CF_API_KEY, RCON_PASSWORD...
#    Resolution order: environment > --env-file > prompt (tty only) > default.
# ---------------------------------------------------------------------------
MC_ROUTER_DOMAIN="${MC_ROUTER_DOMAIN:-mc.local}"
MC_ROUTER_PORT="${MC_ROUTER_PORT:-25565}"
MC_ROUTER_SERVICE_TYPE="${MC_ROUTER_SERVICE_TYPE:-LoadBalancer}"
MCPANEL_USER="${MCPANEL_USER:-admin}"

if [ -t 0 ]; then
  if [ -z "${CF_API_KEY:-}" ]; then
    info "CurseForge API key, needed to download CurseForge modpacks."
    info "Get one at https://console.curseforge.com/ (leave empty to add later)."
    read -r -p "CF_API_KEY: " CF_API_KEY
  fi
  if [ -z "${RCON_PASSWORD:-}" ]; then
    read -r -s -p "RCON password (empty = generate): " RCON_PASSWORD
    echo ""
  fi
  if [ -z "${MCPANEL_PASSWORD:-}" ]; then
    read -r -s -p "Panel admin password (empty = generated by the panel): " MCPANEL_PASSWORD
    echo ""
  fi
fi

if [ -z "${RCON_PASSWORD:-}" ]; then
  RCON_PASSWORD="$(head -c 24 /dev/urandom | base64 | tr -d '/+=' | cut -c1-24)"
  info "Generated RCON password: ${RCON_PASSWORD}"
fi

SECRET_EXISTS=0
if kubectl get secret "$SHARED_ENV_SECRET" -n "$NAMESPACE" > /dev/null 2>&1; then
  SECRET_EXISTS=1
fi

ENV_TMP="$(mktemp /tmp/mc-bootstrap-env.XXXXXX)"
PANEL_VALUES="$(mktemp /tmp/mc-bootstrap-values.XXXXXX.yaml)"
trap 'rm -f "$ENV_TMP" "$PANEL_VALUES"' EXIT

if [ "$SECRET_EXISTS" = "1" ] && [ "${FORCE_SHARED_ENV:-0}" != "1" ] && [ -z "$ENV_FILE" ]; then
  success "Shared Secret '${SHARED_ENV_SECRET}' already exists — keeping it (FORCE_SHARED_ENV=1 to overwrite)"
else
  # --env-file first: the core keys below only apply when not already present
  if [ -n "$ENV_FILE" ]; then
    grep -vE '^\s*(#|$)' "$ENV_FILE" > "$ENV_TMP" || true
  fi
  add_env() {
    grep -q "^$1=" "$ENV_TMP" || printf '%s=%s\n' "$1" "$2" >> "$ENV_TMP"
  }
  add_env EULA "${EULA:-TRUE}"
  add_env MC_ROUTER_DOMAIN "$MC_ROUTER_DOMAIN"
  add_env MC_ROUTER_PORT "$MC_ROUTER_PORT"
  [ -n "${CF_API_KEY:-}" ] && add_env CF_API_KEY "$CF_API_KEY"
  add_env RCON_PASSWORD "$RCON_PASSWORD"
  info "Writing shared Secret '${SHARED_ENV_SECRET}'..."
  kubectl create secret generic "$SHARED_ENV_SECRET" -n "$NAMESPACE" \
    --from-env-file="$ENV_TMP" --dry-run=client -o yaml | kubectl apply -f -
  success "Shared Secret written"
fi

# ---------------------------------------------------------------------------
# 2. mc-router: the single entry point (players connect to <server>.<domain>)
# ---------------------------------------------------------------------------
info ""
info "Installing ${YELLOW}mc-router${NC} chart ${CHART_OCI_PREFIX}/mc-router..."
ROUTER_ARGS=(--set "service.type=$MC_ROUTER_SERVICE_TYPE" --set "service.port=$MC_ROUTER_PORT")
if [ -n "${MC_ROUTER_NODE_PORT:-}" ]; then
  ROUTER_ARGS+=(--set "service.nodePort=$MC_ROUTER_NODE_PORT")
fi
helm upgrade --install minecraft-router "$CHART_OCI_PREFIX/mc-router" \
  --version "${MC_ROUTER_CHART_VERSION:-$DEFAULT_ROUTER_CHART_VERSION}" \
  --namespace "$NAMESPACE" \
  "${ROUTER_ARGS[@]}"
success "mc-router installed"

# ---------------------------------------------------------------------------
# 3. Web panel: starts/stops servers as mc-<server> Helm releases; mounts the
#    Secret from step 1 as /repo/.env and carries the modpack catalog baked in.
# ---------------------------------------------------------------------------

# YAML double-quoted scalar escaping (backslash + quote); values come from the
# operator's environment/prompts so nothing else is expected inside.
yaml_escape() {
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

{
  echo "admin:"
  echo "  user: \"$(yaml_escape "$MCPANEL_USER")\""
  if [ -n "${MCPANEL_PASSWORD:-}" ]; then
    echo "  password: \"$(yaml_escape "$MCPANEL_PASSWORD")\""
  fi
  if [ -n "${K8S_PANEL_HOST:-}" ]; then
    echo "ingress:"
    echo "  enabled: true"
    echo "  host: \"$(yaml_escape "$K8S_PANEL_HOST")\""
  fi
  echo "router:"
  echo "  port: ${MC_ROUTER_PORT}"
  echo "existingSharedEnvSecret: \"${SHARED_ENV_SECRET}\""
} > "$PANEL_VALUES"

info "Installing ${YELLOW}web panel${NC} chart ${CHART_OCI_PREFIX}/web-panel..."
helm upgrade --install minecraft-panel "$CHART_OCI_PREFIX/web-panel" \
  --version "${PANEL_CHART_VERSION:-$DEFAULT_PANEL_CHART_VERSION}" \
  --namespace "$NAMESPACE" \
  --values "$PANEL_VALUES"
success "web panel installed"

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
info ""
info "───────────────────────────────────────────────────────"
success "Stack ready in namespace '${NAMESPACE}' (no repo needed)"
info ""
info "Router address (what players connect to):"
kubectl get svc minecraft-router -n "$NAMESPACE" 2> /dev/null | sed 's/^/  /' || true
info ""
info "Panel:"
info "  kubectl -n $NAMESPACE port-forward svc/minecraft-panel 3777:3777"
info "  -> http://localhost:3777  (user: ${MCPANEL_USER})"
if [ -z "${MCPANEL_PASSWORD:-}" ]; then
  info "  Generated password (printed by the pod on first boot):"
  info "    kubectl -n $NAMESPACE logs deploy/minecraft-panel | grep -i password"
fi
info ""
info "Then open the panel and start any modpack — each one becomes a Helm"
info "release: helm -n $NAMESPACE list shows every running server."
info "Update the shared Secret any time with:"
info "  FORCE_SHARED_ENV=1 $0 $NAMESPACE"
info "───────────────────────────────────────────────────────"
